# Config file for Connor's inference
mutation_rate: !!float 5.69e-9
seq_len: 130000000
output_file: /scratch/djb3ve/connor/inference_output.txt
vcf_file: /scratch/djb3ve/connor/daphnia.filtered.chr.busco.vcf.gz
popinfo_file: /scratch/djb3ve/connor/moments_list.popinfo
pop_names: [Daphnia.pulex.NorthAmerica, Daphnia.pulex.Europe]
num_of_inference_repeats: 5
verbosity: 0
projections: [100, 100]
